### ISSUE TITLE
Azure DevOps does not build release branch

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#3243]
We need to update the configuration so that the release branch builds automatically along with any PRs into the release branch. For future releases, I would like to start building and releasing from there. For 7.12 I am testing the process by preparing a pull request into the release branch and I will release the artifacts that are built with it.

CC @jnm2

**Comment by jnm2** [comment]
We need to stop overriding the yaml by unchecking that checkbox:

![image](https://user-images.githubusercontent.com/8040367/57703552-45046580-762e-11e9-8691-e38b33fd1aad.png)

Then, since we'd no longer have a branch filter, we could optionally replace this in our yaml:

```yaml
trigger:
  branches:
    include: [ '*' ]
    exclude: [ 'refs/tags/*' ]
```

With this:


```yaml
trigger:
  branches:
    include: [ 'master', 'release' ]
    exclude: [ 'refs/tags/*' ]
```
