### ISSUE TITLE
Move dev packages from myget to github packages

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#4440]
Ref the outage yesterday.   Myget seems to be gone:

https://www.reddit.com/r/dotnet/comments/159yigd/is_myget_gone_for_good/
https://github.com/MyGet/MyGetDocs/issues/143

- [x] Remove references to myget package feeds   (@manfred-brands  I believe you have done this already?)
- [ ] Remove appveyor build,
- [ ] Create new build to push master dev packages build to github packages
- [ ] Figure out how much we actually can use github packages
- [ ]  Update README to mention new dev package hosting

**Comment by lahma** [comment]
FYI, I just migrated Quartz.NET to feedz.io, which supports anonymous feeds and has Open Source billing plan (5GB storage instead of free plans 2GB). The management portal supports organizations and repositories under then, also team members with different permissions.

https://github.com/quartznet/quartznet/commit/8ce7d902a9f2691f12deffb3f755dd83306598a1

**Comment by stevenaw** [comment]
There's a link in the README that we should update with the new location for these: https://github.com/nunit/nunit/blob/master/README.md?plain=1#L19

**Comment by manfred-brands** [comment]
We use github packages for work:

Push as:
```
dotnet nuget push --skip-duplicate --source https://nuget.pkg.github.com/nunit/index.json --api-key "${{secrets.GITHUB_TOKEN}}" '*.nupkg'
```

Use as (nuget.config):
```
<add key="NUnitGitHub" value="https://nuget.pkg.github.com/nunit/index.json" />
```

I don't know if user needs a password for a public repository.
For work we have a github enterprise account with internal repositories and have to add the following to setup .net:
```
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
        source-url: https://nuget.pkg.github.com/nunit/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GLOBAL_READ_PACKAGES_SECRET}}
```

Where the GLOBAL_READ_PACKAGES_SECRET is set by our enterprise admins.

The github [documentation](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#about-setting-visibility-and-access-permissions-for-packages) suggests it is not needed.

I guess I can create a build that pushes the package to github and then I can check if I can use it from home.
Watch this space.
